export const allProducts = [
  {
    id: 1,
    name: "Royal Chronograph Elite",
    price: "$12,500",
    originalPrice: "$15,000",
    images: ["/product-1.png"],
    category: "watches",
    categoryName: "Timepieces",
    brand: "Royal Elite",
    shortDesc: "Swiss automatic chronograph • 18K rose gold • 42mm",
    description:
      "An exquisite masterpiece of Swiss horology with sapphire crystal, skeleton movement and premium leather strap.",
    rating: 4.9,
    reviewsCount: 127,
    stock: 8,
    reviews: [
      {
        id: 1,
        name: "Arjun Nair",
        avatar: "/avatars/user1.png",
        rating: 5,
        comment: "Absolutely stunning watch. The finishing and weight feel very premium.",
        date: "2 days ago",
      },
      {
        id: 2,
        name: "Rahul Menon",
        avatar: "/avatars/user2.png",
        rating: 4,
        comment: "Great craftsmanship. Delivery was fast and packaging was luxury.",
        date: "1 week ago",
      },
      {
        id: 3,
        name: "David Thomas",
        avatar: "/avatars/user3.png",
        rating: 5,
        comment: "Worth every penny. Gets compliments everywhere.",
        date: "3 weeks ago",
      },
    ],
  },
  {
    id: 2,
    name: "Astral Diver Pro",
    price: "$9,800",
    originalPrice: null,
    images: ["/product-2.png"],
    category: "watches",
    categoryName: "Timepieces",
    brand: "Astral",
    shortDesc: "300m professional diver • Titanium • Ceramic bezel",
    description:
      "Professional diver watch with ceramic bezel, luminous markers and lightweight titanium case.",
    rating: 4.7,
    reviewsCount: 89,
    stock: 15,
    reviews: [
      {
        id: 1,
        name: "Arjun Nair",
        avatar: "/avatars/user1.png",
        rating: 5,
        comment: "Absolutely stunning watch. The finishing and weight feel very premium.",
        date: "2 days ago",
      },
      {
        id: 2,
        name: "Rahul Menon",
        avatar: "/avatars/user2.png",
        rating: 4,
        comment: "Great craftsmanship. Delivery was fast and packaging was luxury.",
        date: "1 week ago",
      },
      {
        id: 3,
        name: "David Thomas",
        avatar: "/avatars/user3.png",
        rating: 5,
        comment: "Worth every penny. Gets compliments everywhere.",
        date: "3 weeks ago",
      },
    ],
  },
  {
    id: 3,
    name: "Women Modern Bijouterie Set",
    price: "$12,500",
    originalPrice: null,
    images: ["https://images.unsplash.com/photo-1611590027211-b954fd027b51?w=800&q=80"],
    category: "bijouterie",
    categoryName: "Fine Jewelry",
    brand: "Luxe Bijoux",
    shortDesc: "18K white gold • Diamonds & sapphires",
    description:
      "Contemporary fine jewelry set crafted in 18K white gold with ethically sourced gemstones.",
    rating: 4.8,
    reviewsCount: 62,
    stock: 5,
  },
  {
    id: 4,
    name: "Heritage Automatic Dress Watch",
    price: "$15,800",
    originalPrice: null,
    images: ["https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80"],
    category: "watches",
    categoryName: "Timepieces",
    brand: "Heritage",
    shortDesc: "Hand-wound movement • Guilloché dial",
    description:
      "Timeless dress watch with hand-wound mechanical movement and classic guilloché dial.",
    rating: 4.95,
    reviewsCount: 204,
    stock: 3,
  },
  {
    id: 5,
    name: "Emerald Chain Bag",
    price: "$4,200",
    originalPrice: null,
    images: ["https://images.unsplash.com/photo-1584917865447-032f09c18ef1?w=800&q=80"],
    category: "accessories",
    categoryName: "Handbags",
    brand: "Luxe Atelier",
    shortDesc: "Emerald calf leather • Gold chain hardware",
    description: "Structured calf leather bag with gold chain strap and elegant silhouette.",
    rating: 4.6,
    reviewsCount: 48,
    stock: 12,
  },
  {
    id: 6,
    name: "Abstract No. 7 – Limited Edition Print",
    price: "$1,850",
    originalPrice: null,
    images: ["https://images.unsplash.com/photo-1579783902614-a3db7a7e6e8e?w=800&q=80"],
    category: "fine-art",
    categoryName: "Fine Art",
    brand: "Gallery Modern",
    shortDesc: "Giclée print • Signed & numbered",
    description: "Museum-quality giclée print on archival paper. Signed and numbered edition.",
    rating: 5.0,
    reviewsCount: 19,
    stock: 25,
  },
  {
    id: 7,
    name: "Midnight Blue Chrono",
    price: "$9,200",
    originalPrice: "$11,500",
    images: [
      "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=800&q=80",
      "https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=800&q=80",
    ],
    category: "watches",
    categoryName: "Timepieces",
    brand: "Midnight",
    shortDesc: "Blue sunburst dial • Chronograph",
    description: "Sport-luxury chronograph with deep blue sunburst dial and stainless steel case.",
    rating: 4.8,
    reviewsCount: 76,
    stock: 9,
  },
  {
    id: 8,
    name: "Sapphire Eternity Ring",
    price: "$8,900",
    originalPrice: null,
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80",
      "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800&q=80",
    ],
    category: "bijouterie",
    categoryName: "Fine Jewelry",
    brand: "Eternal Gems",
    shortDesc: "18K white gold • Blue sapphires",
    description: "Full eternity ring set with premium blue sapphires symbolizing everlasting love.",
    rating: 5.0,
    reviewsCount: 34,
    stock: 7,
  },
  {
    id: 9,
    name: "Classic Leather Tote",
    price: "$3,600",
    originalPrice: null,
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80",
      "https://images.unsplash.com/photo-1584917865447-032f09c18ef1?w=800&q=80",
    ],
    category: "accessories",
    categoryName: "Handbags",
    brand: "Luxe Atelier",
    shortDesc: "Italian full-grain leather • Everyday tote",
    description: "Timeless Italian leather tote with spacious compartments for daily use.",
    rating: 4.7,
    reviewsCount: 53,
    stock: 18,
  },
  {
    id: 10,
    name: "Oceanic Moonphase",
    price: "$14,200",
    originalPrice: "$16,900",
    images: [
      "https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=800&q=80",
      "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80",
    ],
    category: "watches",
    categoryName: "Timepieces",
    brand: "Oceanic",
    shortDesc: "Moonphase complication • Blue dial",
    description: "Elegant moonphase watch combining astronomy and fine Swiss watchmaking.",
    rating: 4.85,
    reviewsCount: 94,
    stock: 6,
  },
  // WATCHES - HIS
  {
    id: 11,
    name: "Titanium Explorer",
    price: "$10,200",
    originalPrice: null,
    images: ["https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800&q=80"],
    category: "watches",
    categoryName: "Timepieces",
    subCategory: "his",
    brand: "Explorer",
    shortDesc: "Titanium case • Adventure edition",
    description:
      "Built for explorers with rugged titanium case and high precision automatic movement.",
    rating: 4.8,
    reviewsCount: 40,
    stock: 10,
  },

  // WATCHES - HER
  {
    id: 12,
    name: "Rose Gold Petite",
    price: "$7,600",
    originalPrice: null,
    images: ["https://images.unsplash.com/photo-1518544801976-3e159e50e5bb?w=800&q=80"],
    category: "watches",
    categoryName: "Timepieces",
    subCategory: "her",
    brand: "Petite",
    shortDesc: "Rose gold • Elegant dial",
    description: "Elegant women's watch with rose gold case and minimal dial design.",
    rating: 4.9,
    reviewsCount: 55,
    stock: 14,
  },

  // HANDBAGS - HER
  {
    id: 13,
    name: "Velvet Evening Clutch",
    price: "$2,400",
    originalPrice: null,
    images: ["https://images.unsplash.com/photo-1593032465171-8c2f36a7c41f?w=800&q=80"],
    category: "accessories",
    categoryName: "Handbags",
    subCategory: "her",
    brand: "Velour",
    shortDesc: "Velvet finish • Gold clasp",
    description: "Luxury velvet evening clutch designed for elegant occasions.",
    rating: 4.7,
    reviewsCount: 21,
    stock: 11,
  },

  // HANDBAGS - HIS
  {
    id: 14,
    name: "Executive Leather Briefcase",
    price: "$4,800",
    originalPrice: null,
    images: ["https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&q=80"],
    category: "accessories",
    categoryName: "Handbags",
    subCategory: "his",
    brand: "Executive",
    shortDesc: "Italian leather • Business edition",
    description: "Professional leather briefcase crafted from premium Italian leather.",
    rating: 4.8,
    reviewsCount: 32,
    stock: 9,
  },

  // BIJOUTERIE - HER
  {
    id: 15,
    name: "Diamond Halo Necklace",
    price: "$11,500",
    originalPrice: null,
    images: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80"],
    category: "bijouterie",
    categoryName: "Fine Jewelry",
    subCategory: "her",
    brand: "Halo",
    shortDesc: "Diamond halo • White gold",
    description: "Luxury diamond halo necklace set in 18K white gold.",
    rating: 4.9,
    reviewsCount: 38,
    stock: 6,
  },

  // BIJOUTERIE - HIS
  {
    id: 16,
    name: "Onyx Signet Ring",
    price: "$5,300",
    originalPrice: null,
    images: ["https://images.unsplash.com/photo-1588444650733-df7c0c9a6f18?w=800&q=80"],
    category: "bijouterie",
    categoryName: "Fine Jewelry",
    subCategory: "his",
    brand: "Regal",
    shortDesc: "Black onyx • Gold ring",
    description: "Classic men's signet ring featuring polished black onyx stone.",
    rating: 4.8,
    reviewsCount: 29,
    stock: 8,
  },

  // ART (NO SUB CATEGORY)
  {
    id: 17,
    name: "Golden Horizon Canvas",
    price: "$2,100",
    originalPrice: null,
    images: ["https://images.unsplash.com/photo-1549887534-3ec93abae6c7?w=800&q=80"],
    category: "fine-art",
    categoryName: "Fine Art",
    brand: "Modern Atelier",
    shortDesc: "Oil on canvas • Limited edition",
    description: "Original oil painting inspired by abstract golden landscapes.",
    rating: 4.9,
    reviewsCount: 12,
    stock: 4,
  },

  {
    id: 18,
    name: "Minimalist Shapes Series",
    price: "$1,450",
    originalPrice: null,
    images: ["https://images.unsplash.com/photo-1579783901586-d88db74b4fe4?w=800&q=80"],
    category: "fine-art",
    categoryName: "Fine Art",
    brand: "Studio Abstract",
    shortDesc: "Abstract print • Limited series",
    description: "Modern geometric abstract artwork printed on archival paper.",
    rating: 4.7,
    reviewsCount: 16,
    stock: 12,
  },
];
