export const products = [
  // WATCHES
  {
    id: 1,
    name: "Classic Leather Watch",
    category: "watches",
    brand: "Timex",
    price: 3499,
    rating: 4.5,
    image: "/images/watches/watch1.jpg",
    description: "Elegant analog watch with leather strap.",
  },
  {
    id: 2,
    name: "Smart Fitness Watch",
    category: "watches",
    brand: "Noise",
    price: 2999,
    rating: 4.3,
    image: "/images/watches/watch2.jpg",
    description: "Smartwatch with health and fitness tracking.",
  },
  {
    id: 3,
    name: "Luxury Metal Watch",
    category: "watches",
    brand: "Fossil",
    price: 8999,
    rating: 4.7,
    image: "/images/watches/watch3.jpg",
    description: "Premium stainless steel chronograph watch.",
  },
  {
    id: 4,
    name: "Minimal Black Watch",
    category: "watches",
    brand: "Daniel Wellington",
    price: 7499,
    rating: 4.4,
    image: "/images/watches/watch4.jpg",
    description: "Minimal design for formal wear.",
  },
  {
    id: 5,
    name: "Digital Sports Watch",
    category: "watches",
    brand: "Casio",
    price: 2499,
    rating: 4.6,
    image: "/images/watches/watch5.jpg",
    description: "Durable digital watch with water resistance.",
  },
  {
    id: 6,
    name: "Automatic Skeleton Watch",
    category: "watches",
    brand: "Titan",
    price: 11999,
    rating: 4.6,
    image: "/images/watches/watch6.jpg",
    description: "Automatic watch with skeleton dial.",
  },
  {
    id: 7,
    name: "Sport Analog Watch",
    category: "watches",
    brand: "Sonata",
    price: 1999,
    rating: 4.2,
    image: "/images/watches/watch7.jpg",
    description: "Affordable everyday analog watch.",
  },
  {
    id: 8,
    name: "Premium Smart Watch",
    category: "watches",
    brand: "Samsung",
    price: 15999,
    rating: 4.8,
    image: "/images/watches/watch8.jpg",
    description: "Premium smartwatch with AMOLED display.",
  },
  {
    id: 9,
    name: "Chronograph Watch",
    category: "watches",
    brand: "Citizen",
    price: 9999,
    rating: 4.5,
    image: "/images/watches/watch9.jpg",
    description: "Chronograph watch with date display.",
  },
  {
    id: 10,
    name: "Military Style Watch",
    category: "watches",
    brand: "Fastrack",
    price: 3299,
    rating: 4.3,
    image: "/images/watches/watch10.jpg",
    description: "Rugged watch with military-inspired design.",
  },

  // BAGS
  {
    id: 11,
    name: "Laptop Backpack",
    category: "bags",
    brand: "American Tourister",
    price: 2799,
    rating: 4.5,
    image: "/images/bags/bag1.jpg",
    description: "Backpack with padded laptop compartment.",
  },
  {
    id: 12,
    name: "Travel Duffel Bag",
    category: "bags",
    brand: "Wildcraft",
    price: 3199,
    rating: 4.4,
    image: "/images/bags/bag2.jpg",
    description: "Spacious duffel bag for travel.",
  },
  {
    id: 13,
    name: "Leather Office Bag",
    category: "bags",
    brand: "Hidesign",
    price: 6499,
    rating: 4.6,
    image: "/images/bags/bag3.jpg",
    description: "Premium leather office bag.",
  },
  {
    id: 14,
    name: "Sling Bag",
    category: "bags",
    brand: "Puma",
    price: 1799,
    rating: 4.2,
    image: "/images/bags/bag4.jpg",
    description: "Compact sling bag for daily use.",
  },
  {
    id: 15,
    name: "Gym Backpack",
    category: "bags",
    brand: "Adidas",
    price: 2599,
    rating: 4.3,
    image: "/images/bags/bag5.jpg",
    description: "Lightweight gym and travel backpack.",
  },
  {
    id: 16,
    name: "College Backpack",
    category: "bags",
    brand: "Skybags",
    price: 2199,
    rating: 4.4,
    image: "/images/bags/bag6.jpg",
    description: "Stylish backpack for college students.",
  },
  {
    id: 17,
    name: "Trolley Travel Bag",
    category: "bags",
    brand: "Safari",
    price: 8999,
    rating: 4.5,
    image: "/images/bags/bag7.jpg",
    description: "Large trolley bag for long trips.",
  },
  {
    id: 18,
    name: "Mini Backpack",
    category: "bags",
    brand: "Lavie",
    price: 1999,
    rating: 4.3,
    image: "/images/bags/bag8.jpg",
    description: "Trendy mini backpack.",
  },
  {
    id: 19,
    name: "Messenger Bag",
    category: "bags",
    brand: "F Gear",
    price: 2899,
    rating: 4.4,
    image: "/images/bags/bag9.jpg",
    description: "Messenger bag for office and casual use.",
  },
  {
    id: 20,
    name: "Camera Backpack",
    category: "bags",
    brand: "Lowepro",
    price: 7499,
    rating: 4.7,
    image: "/images/bags/bag10.jpg",
    description: "Protective backpack for camera gear.",
  },
];
